[package]
name = "furbooru_markdown"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "furbooru_markdown"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
comrak = "0.7"
lazy_static = "1.0"
rustler = "0.21.1"
